version: '3.8'

services:
  rims-ingress:
    image: nginx:latest
    container_name: rims-ingress
    volumes:
      - ./src/rims-ingress/nginx.conf:/etc/nginx/nginx.conf
      - ./src/rims-ingress/logs/:/etc/nginx/logs/
    ports:
      - 8080:8080
      - 8888:8888
  rims-frontend:
    image: rims-frontend
    container_name: rims-frontend
    build:
      context: ./src/rims-frontend/
      dockerfile: ./Dockerfile
    expose:
      - 80
    environment:
      - API_URI 
  rims-api:
    image: rims-api
    container_name: rims-api
    build:
      context: ./src/rims-api
      dockerfile: ./Dockerfile
    expose:
      - 80
    environment:
      - AZUREWEBJOBSSTORAGE
      - COSMOSDBCONNECTIONSTRING
      - ASSETSSTORAGECONNECTIONSTRING
    volumes:
      - ./src/rims-api:/home/site/wwwroot
      
