version: '3.8'

services:
  # Dev Specific Images
  rims-ingress:
    image: nginx:latest
    container_name: rims-ingress
    volumes:
      - ./src/rims-ingress/nginx.conf:/etc/nginx/nginx.conf
      - ./src/rims-ingress/logs/:/etc/nginx/logs/
      - ./lib/ssl/:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443
  rims-frontend:
    image: rims-frontend
    container_name: rims-frontend
    build:
      context: ./src/rims-frontend/
      dockerfile: ./Dockerfile
    expose:
      - 3000
    environment:
      - ADB2C_AUTHORITY
      - ADB2C_CLIENT_ID
      - ADB2C_KNOWN_AUTHORITIES
      - ADB2C_POST_LOGOUT_REDIRECT_URI
      - ADB2C_REDIRECT_URI
      - ADB2C_SIGNUP_SIGNIN_POLICY
      - API_URI
    volumes:
      - ./src/rims-frontend/:/app
  rims-api:
    image: rims-api
    container_name: rims-api
    build:
      context: ./src/rims-api
      dockerfile: ./Dockerfile
    expose:
      - 80
      - 9229
    ports:
      - 5858:9229
    environment:
      - ADB2C_AUTHORITY
      - ADB2C_CLIENT_ID
      - ADB2C_KNOWN_AUTHORITIES
      - ADB2C_POST_LOGOUT_REDIRECT_URI
      - ADB2C_REDIRECT_URI
      - ADB2C_SIGNUP_SIGNIN_POLICY
      - ASSETSSTORAGECONNECTIONSTRING
      - AZUREWEBJOBSSTORAGE
      - COSMOSDBCONNECTIONSTRING
    volumes:
      - ./src/rims-api:/home/site/wwwroot
  # Production Specific Images
  rims-frontend-prod:
    image: rims-frontend
    container_name: rims-frontend
    build:
      context: ./src/rims-frontend/
      dockerfile: ./Dockerfile.prod
    expose:
      - 80
    environment:
      - ADB2C_AUTHORITY
      - ADB2C_CLIENT_ID
      - ADB2C_KNOWN_AUTHORITIES
      - ADB2C_POST_LOGOUT_REDIRECT_URI
      - ADB2C_REDIRECT_URI
      - ADB2C_SIGNUP_SIGNIN_POLICY
      - API_URI
